version: '3.8'
services:
  stats-client:
    build: stats-client
    image: stats-client-image
    container_name: stats-client-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-service
    environment:
      - SERVICE_URL=http://stats-service:7070

  stats-server:
    build: stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "7070:7070"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  server:
    build: server
    image: server-image
    container_name: server-container
    ports:
      - "8080:8080"

  db:
    image: postgres:13.7-alpine
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password